---
micronaut:
    application:
        name: twitter-images-kotlin

---
micronaut:
    metrics:
        enabled: true
    security:
        enabled: true

app.security:
  admin:
    user: admin
    password: admin
    role: ROLE_ADMIN
  test: Mytest
  users:
    - user: user
      password: password
      role: VIEWER
    - user: editoruser
      password: somestrongpassword
      role: EDITOR
    - user: admin
      password: admin
      role: ADMIN
---
mongodb:
    uri: "mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}"